- name: Install required RPM packages
  community.general.rpm_ostree_pkg:
    name: 
      - kubelet
      - kubeadm
      - crio
  register: layersAdded

- name: Reboot if required
  reboot:
  when: layersAdded.changed

- include_tasks: services.yml
